---
logging:
  level: INFO
  loggers:
    com.github.windbender.timeit: DEBUG
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
